version: '2'
services:
  redis:
    restart: always
    image: redis

  php-fpm:
    build: ./docker/php-oci
    links:
      - redis
    volumes:
      - "./arb-platform:/app"
    environment:
      LD_LIBRARY_PATH: "/opt/oracle/instantclient_12_1"

  nginx:
    image: nginx
    volumes:
      - "./arb-platform:/app"
      - "./docker/nginx-dev/vhost.conf:/etc/nginx/conf.d/default.conf"
      - "./docker/nginx-dev/nginx.conf:/etc/nginx/nginx.conf"
    links:
      - php-fpm
    ports:
      - "8078:80"

